#pragma once
#ifndef __ENUM_H__
#define __ENUM_H__


namespace OBJID
{
	enum ID { PLAYER,PLAYER_UI, PLAER_WEAPON, GOLD, MONSTER,  MONSTER_WEAPON, UI, SAVEPOINT, ITEM, END };
}

namespace TILE
{
	enum TYPE { SURFACE,WALL,CEILING, NOTHING, BOUNCE,THIN, LADDER, HARD,OBJECT, THORN, ORB,MOVING, END };
}
namespace MONSTER
{
	enum TYPE { MONKEY, SHIELD, JUMPING, BOMB, BIGPLANT, Chest, END };
}
namespace STAGE
{
	enum CHANNEL
	{
		STAGE1_1, STAGE1_2, STAGE1_3, STAGE1_4, STAGE1_5,
		STAGE1_6, STAGE1_7, STAGE1_8, STAGE1_9, STAGE1_10,
		STAGE1_11, STAGE1_12, STAGE1_13, STAGE1_14, STAGE1_15,
		STAGE1_16, END
	};
}

namespace GROUPID
{
	enum ID { BACKGROUND, OBJECT, PLAYER, EFFECT, UI, END };
}
#endif // !__ENUM_H__
